apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: newb-t-BE
  description: newbt Back End
  tags:
    - there
    - be
    - treasure
  links:
    - url: https://github.com/shukilagama/newb-t

spec:
  type: repo
  lifecycle: production
  owner: team-a
  system: artist-engagement-portal
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: newbt-FE
  description: newbt Front End
  tags:
    - here
    - oingo
    - boingo
  links:
    - url: https://github.com/shukilagama/newb-t

spec:
  type: bongos
  lifecycle: production
  owner: team-a
  system: repos
