/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example

import org.springframework.web.context.ServletContextAware;
import org.apache.logging.log4j.core.impl.Log4jContextFactory;
import com.fasterxml.jackson.databind.ObjectMapper;
import io.jsonwebtoken.SigningKeyResolverAdapter;

object App {
  def main(args: Array[String]): Unit = {
    println(greeting())
  }

  def greeting(): String = "Hello, world!"
}
